# fly.toml app configuration file generated for 0x99m-portfolio on 2025-10-31T10:47:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '0x99m-portfolio'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
